<?php
# CMS - CMS Made Simple
# (c)2004 by Ted Kulp (tedkulp@users.sf.net)
# Visit our homepage at: http://www.cmsmadesimple.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# BUT withOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#$Id: class.content.inc.php 6905 2011-02-20 22:23:40Z calguy1000 $

namespace CMSMS\internal;

/**
 * @package CMS
 */

/**
 * Helper class to deal with parsing or fetching content blocks.
 *
 * @author      Robert Campbell <calguy1000@cmsmadesimple.org>
 * @since		1.11
 * @ignore
 * @internal
 * @package		CMS
 */
final class content_plugins
{
    private static $_priority;
    private static $_contentBlocks;
    private static $_primary_content;    // generated by preprocess_mact
    private function __construct() {}

    private static function content_return($result, &$params, &$smarty)
    {
        // this is a smarty tempalte, not the global smarty instance
        if ( !empty($params['assign']) ) {
            $smarty->assign(trim($params['assign']), $result);
        }
        else {
            echo $result;
        }
    }

    public static function get_content_blocks()
    {
        return self::$_contentBlocks;
    }

    public static function reset()
    {
        self::$_priority = 100;
        self::$_contentBlocks = null;
    }

    /**
     * Compile a content block tag into PHP code.
     * On Frontend requests {content} is a compiler tag (this function) that gnerates php code that will fetch the content block.
     * this allows for numerous functionalities, including pre-processing the mact and permissions.
     */
    public static function smarty_compile_fecontentblock($params,$template)
    {
        $ptext = 'array(';
        $tmp = array();
        foreach($params as $k => $v) {
            $tmp[] .= '\''.$k.'\'=>'.$v;
        }
        $ptext .= implode(',',$tmp);
        $ptext .= ')';
        return '<?php \CMSMS\\internal\\content_plugins::smarty_internal_fetch_contentblock('.$ptext.',$_smarty_tpl); ?>';
    }

    /**
     * This is handling of the {content} blocks.
     *
     * once we determine the content block to render, we use the $smarty->fetch() method to request the content: resource
     * to process the value of the content blocks through smarty.
     *
     * @since 1.11
     * @author calguy1000
     * @internal
     * @ignore
     */
    public static function smarty_internal_fetch_contentblock($params,&$smarty)
    {
        $contentobj = \CmsApp::get_instance()->get_content_object();
        $result = null;
        if (is_object($contentobj)) {
            if( !$contentobj->IsPermitted() ) throw new CmsError403Exception();
            $block = (isset($params['block']))?$params['block']:'content_en';
            // if content_en
            //    get primary content
            // otherwise other block
            $output = null;
            if( $block == 'content_en' ) {
                // was the data prefetched ?
                $result = self::get_default_content_block_content( $contentobj->Id(), $smarty );
            }
            if( !$result ) {
                if( isset($_SESSION['__cms_preview__']) && $contentobj->Id() == __CMS_PREVIEW_PAGE__ ) {
                    // note: content precompile/postcompile events will not be triggererd in preview.
                    //$val = $contentobj->Show($block);
                    //$result = $smarty->fetch('eval:'.$val);
                    $result = $smarty->fetch(str_replace(' ', '_', 'content:' . $block), '|'.$block, $contentobj->Id().$block);
                }
                else {
                    $result = $smarty->fetch(str_replace(' ', '_', 'content:' . $block), '|'.$block, $contentobj->Id().$block);
                }
            }
        }
        return self::content_return($result, $params, $smarty);
    }

    public static function smarty_fetch_pagedata($params,$smarty)
    {
        $contentobj = \CmsApp::get_instance()->get_content_object();
        if( !is_object($contentobj) || $contentobj->Id() <= 0 ) return self::content_return('', $params, $smarty);

        $result = $smarty->fetch('content:pagedata','',$contentobj->Id());
        if( isset($params['assign']) ){
            $smarty->assign(trim($params['assign']),$result);
            return;
        }
        return $result;
    }

    public static function smarty_fetch_imageblock($params,&$smarty)
    {
        $ignored = [ 'block','type','name','label','upload','dir','default','tab','priority','exclude','sort', 'profile', 'urlonly','assign' ];
        $gCms = \CmsApp::get_instance();
        $contentobj = $gCms->get_content_object();
        if( !is_object($contentobj) || $contentobj->Id() <= 0 ) return self::content_return('', $params, $smarty);

        $config = \cms_config::get_instance();
        $adddir = \cms_siteprefs::get('contentimage_path');
        if( isset($params['dir']) && $params['dir'] != '' ) $adddir = $params['dir'];
        $dir = cms_join_path($config['uploads_path'],$adddir);
        $basename = basename($config['uploads_path']);

        $result = '';
        if( isset($params['block']) ) {
            $result = $smarty->fetch(str_replace(' ', '_', 'content:' . $params['block']), '|'.$params['block'], $contentobj->Id().$params['block']);
        }
        $img = $result;

        $out = null;
        if( startswith(realpath($dir),realpath($basename)) ) {
            if( ($img == -1 || empty($img)) && isset($params['default']) && $params['default'] ) $img = $params['default'];

            if( $img != -1 && !empty($img) ) {
                // create the absolute url.
                $orig_val = $img;
                $img = CMS_UPLOADS_URL.'/';
                if( $adddir ) $img .= $adddir.'/';
                $img .= $orig_val;

                $urlonly = cms_to_bool(get_parameter_value($params,'urlonly'));
                if( $urlonly ) {
                    $out = $img;
                }
                else {
                    $tagparms = [];
                    foreach( $params as $key => $val ) {
                        $key = trim($key);
                        if( !$key ) continue;
                        $val = trim($val);
                        if( !$val ) continue;
                        if( in_array($key,$ignored) ) continue;
                        $tagparms[$key] = $val;
                    }

                    $out = "<img src=\"$img\"";
                    foreach( $tagparms as $key => $val ) {
                        $out .= " $key=\"$val\"";
                    }
                    $out .= '/>';
                }
            }
        }
        if( isset($params['assign']) ){
            $smarty->assign(trim($params['assign']),$out);
            return;
        }
        return $out;
    }

    public static function smarty_fetch_moduleblock($params,&$smarty)
    {
        $result = '';
        $key = '';

        if( !isset($params['block']) ) return;
        $block = $params['block'];

        $gCms = \CmsApp::get_instance();
        $content_obj = $gCms->get_content_object();
        if( is_object($content_obj) ) {
            $result = $content_obj->GetPropertyValue($block);
            if( $result == -1 ) $result = '';
            $module = isset($params['module']) ? trim($params['module']) : null;
            if( $module ) {
                $mod = \cms_utils::get_module($module);
                if( is_object($mod) ) $result = $mod->RenderContentBlockField($block,$result,$params,$content_obj);
            }
        }

        if( isset($params['assign']) ) {
            $smarty->assign($params['assign'],$result);
            return;
        }
        return $result;
    }

    public static function smarty_fetch_textblock($params, $smarty)
    {
        // never returns content on frontend requests
        return;
    }

    public static function get_default_content_block_content( $page_id, &$smarty)
    {
        // this is what preprocessess the mact (before template processing, depending on config entries).
        // and caches the result in memory.
        $result = null;
        if( self::$_primary_content ) return self::$_primary_content;

        $do_mact = $module = $id = $action = $inline = null;
        if( isset($_REQUEST['mact']) ) {
            list($module,$id,$action,$inline) = explode(',',$_REQUEST['mact'],4);
            // do not process inline content.
            if( $module && !$inline && $id == 'cntnt01' ) $do_mact = true;
        }

        if( $do_mact ) {
            $modops = \ModuleOperations::get_instance();
            $module_obj = $modops->get_module_instance($module);
            if( !$module_obj ) {
                // module not found... couldn't even autoload it.
                @trigger_error('Attempt to access module '.$module.' which could not be found (is it properly installed and configured?');
                throw new \CmsError404Exception('Attempt to access module '.$module.' which could not be found (is it properly installed and configured?');
            }
            if( !$module_obj->IsPluginModule() ) {
                @trigger_error('Attempt to access module '.$module.' on a frontend request, which is not a plugin module');
                throw new \CmsError404Exception('Attempt to access module '.$module.' which could not be found (is it properly installed and configured?');
            }

            @ob_start();
            $parms = $modops->GetModuleParameters($id);
            $result = $module_obj->DoActionBase($action, $id, $parms, $page_id, $smarty);

            if( $result !== FALSE ) echo $result;
            $result = @ob_get_contents();
            @ob_end_clean();
        }
        else {
            $block = 'content_en';
            if( isset($_SESSION['__cms_preview__']) && $page_id == -100 ) {
                // note: content precompile/postcompile events will not be triggererd in preview.
                //$val = $contentobj->Show($block);
                //$result = $smarty->fetch('eval:'.$val);
                $result = $smarty->fetch(str_replace(' ', '_', 'content:' . $block), '|'.$block, $page_id.$block);
            }
            else {
                $result = $smarty->fetch(str_replace(' ', '_', 'content:' . $block), '|'.$block, $page_id.$block);
            }
        }
        self::$_primary_content = $result;
        return $result;
    }

} // end of class.
